language: node_js
node_js:
- '6'
before_script:
- mysql -u travis < db/schema.sql
script:
- npm start &
- npm test
deploy:
  provider: heroku
  api_key:
    secure: fbk0LTSoxADewMtR4GXZVD66/NFoXVjjHj3lTv7d+7GvOqww0DTciTxV/IfatK4oiv+kvbsp/lLuarmiT6GGmMWFq9qRqNZxT+NI38uKg8Dry6TXZrJC4LPnxTq3XhEZHyWmWOwnG4/lJ/0yAdpKsmiDa5I+so2oGp8TQngkcWGYlimOxdU31tmXwSqcg3Re6RhM8n9lMBHl/lUAW0IfzJp+H41i3WC4XFQ1lK+0i78gzNexAxTLTzCfH0kxsEKa7OSJ9AZYBSESUlMQx3mpbjoxrmqemczJof/SweOf4W+Ydt9BE4+tMlLjksKAcrCVr60dJkTa3szbc81bZ/2vt0eSQ+vSUgQZiAYRjVa1nAyEgu4EE9aeE45DSBZydl+Fs2ftCTf/8AkDQrplc1ua45VDbpLv0qKdYJr/qv/uWq1RYR01VY52XaxCRTKDTMhgsQySalfPpmeTBetK4cnlFUHso23vEUQ0kkfQGZDRN1ur8uF4x1u5DfoU1Mzp1O7lNjhN6DYZqMKCn+N/Ru5XFo3XP6+w7oqRTcSKBwkGJyTOMey9QmSmmnOXqCpVLIzXKGjNSoP1PxA26Bkjck5uHrdAA8BNCYfyvKN6A90Uf7BZ/GRX8ikrSLnoYiYiLfUCmMF2e6tnzul9YGw48aaMkSxPZAj4ruSQOLi0YWaNhgQ=
  app: react-ion-api
  on:
    repo: React-Ion/React-Ion-API
