language: node_js
node_js:
- '6'
before_script:
- mysql -u travis < db/schema.sql
script:
- npm start &
- npm test
deploy:
  provider: heroku
  api_key:
    secure: G2TqcnYQ0a7GSol7TtjaH2qmYzFKNCyGrD4kxtLBKIqOCRSyG3oH1xYQvgMeAgoXPcss9G2s6YZCz9L7nyMrnW6bU1ZKWXHBYdQwO/i6qm+kikf5n6RzbryZobJJ0DzmYpIwTr15koWyigDZFxN4NlwQ4AvIc65L6nM6AHhqSw8b14JII80gsR6KXNk7Y5ISgn6DmhkM1QTMB/6PC8PSx7s8Z56zASL2ITu1ZmYPrni173PsekFovOHSbwK6CmJDuPllVLdqDHF2s4rrk1iQpjCy/nhpEMAFyIKK7nlhKAzA264HpacIT7/pE8PjHkTdYmFPbztXjJGxnrI2iEgr/w5GDXEWp587cfsI5ZM0Po5yTMRvaC140lngHb4pPEeU0sYuNn3w+7UixVDyxX+VPzuI6y7IDguszrPLV+LM97efH6KbdxjzZgFhnZ8OJCiyzbT1p7KWUVamnbKf0Pu5UvUoPiOK4drDMLMiFLBx2F1qE1bZm/nWqTg4ybJbo6q5NpCnFb/L4DsxoiY4mz4Mz8wser2GV5Zx45HUBPm3Z1Wd7wmfDSR0o4RfTj+9MfTuuLRnbrw3so2J/QiiSYtJXniFd9mZsLZAPfXy/EyFiUyLwhod4mTV0QwMLt9QJ/+xynOIJdd1e44GirxY0JXTN4cWn7FqdQqt9ns5CqNn6m0=
  app: react-ion-api
  on:
    repo: React-Ion/React-Ion-API
